ConvertToDecimalInt method implemented
fjcoding/AT10 pull request #4
Opened 2019-05-24 17:20 UTC by LimbertVargas

I have just finished implementing the code, please review it.
Regards

2019-05-24 21:10 UTC, J0c4 requested changes
Good, solution works as expected, need to address my comments in the PR

2019-05-24 21:10 UTC, J0c4 commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Do we really need to version this file? if not, let's add it to `.gitignore`

2019-05-24 21:10 UTC, J0c4 commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
Do we really need to version this file? if not, let's add it to `.gitignore`

2019-05-24 21:10 UTC, J0c4 commented on src/main/java/binaries/limbert/BinaryArray.java
> +        //throw new UnsupportedOperationException("Not supported yet.");
Please remove commented line

2019-05-24 21:10 UTC, J0c4 commented on src/main/java/binaries/limbert/BinaryArray.java
> +    	int longitud = binaries.length;
Let's use english as standard for names in the code

2019-05-24 21:10 UTC, J0c4 commented on src/main/java/binaries/limbert/BinaryArray.java
> +		int dec = 0;
be aware of the abbreviated names, sometimes they are not as meaningful as their non-abbreviated version

2019-05-24 21:10 UTC, J0c4 commented on src/main/java/binaries/limbert/BinaryArray.java
> +			dec = dec+binaries[i] * (int) Math.pow(2, longitud-1 - i);
spaces missing before and after `+` `-` operators. Plus `2` like magic number

2019-05-27 17:57 UTC, J0c4 commented
Hello @LimbertVargas - You latests updates look good, however, the `.classpath` and `.project` still need to be deleted. Did you run `git rm .classpath` and `git rm .project`? those should remove the files

2019-05-27 18:39 UTC, LimbertVargas commented
Hello Jose,
I will delete it, Thank you

Regards,

[Fundacion Jala]
Limbert Alvaro Vargas Laura
Becario - Fundacion Jala
________________________________
From: Jose Carlos <notifications@github.com>
Sent: Monday, May 27, 2019 1:57 PM
To: fjcoding/AT10
Cc: Limbert Vargas Laura; Mention
Subject: Re: [fjcoding/AT10] ConvertToDecimalInt method implemented (#4)


Hello @LimbertVargas<https://github.com/LimbertVargas> - You latests updates look good, however, the .classpath and .project still need to be deleted. Did you run git rm .classpath and git rm .project? those should remove the files

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/fjcoding/AT10/pull/4?email_source=notifications&email_token=ALZHRNFIRF375JKY3IG744TPXQOJ3A5CNFSM4HPRKDC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKJF6Y#issuecomment-496276219>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ALZHRNACFWWUKG6E4LLZOADPXQOJ3ANCNFSM4HPRKDCQ>.

2019-05-27 21:51 UTC, merged